### ISSUE TITLE
The theme should perhaps add itself to `custom-theme-load-path`

### ISSUE THREAD

**Issue by kenranunderscore** [fredcamps/green-is-the-new-black-emacs#2]
Most other themes are doing something like
```elisp
;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))
```
to add their source location to `custom-theme-load-path`.

In my case this manifested as the theme not showing up when doing `load-theme` due to it being installed under `.emacs.d/.local/straight/repos/green-is-the-new-black-emacs/`.

**Comment by fredcamps** [comment]
@kenranunderscore Hi mate, sorry for the late respond, I'll include this on the next version, Thank you...

**Comment by fredcamps** [comment]
@kenranunderscore is already on master
